[package]
name = "myforms_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4"
lambda-web = { version = "0.2", features = ["actix4"] }
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1", features = ["full"] }
